### ISSUE TITLE
aws-ssh (0.0.1) Missing README.md

### ISSUE THREAD

**Issue by rfoos** [arusahni/aws-ssh#3]
pip install aws-ssh fails on version 0.0.1 because README.md is not included in the root directory (below), or there needs to be a test in setup.py to see if the file exists.

Workaround:
  tar xf aws-ssh-0.0.1.tar.gz
  cd aws-ssh-0.0.1
  touch README.md
  python setup.py install

---
pip install aws-ssh
Collecting aws-ssh
  Using cached https://files.pythonhosted.org/packages/81/3e/a9ec548bd7c1895ded22b9ef381b3fc99a45c10a60f85bfbca73f7f6b6b7/aws-ssh-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xv/qzlfq_7d7nqf5jlx7s_np9jw0000gq/T/pip-install-35o4f14h/aws-ssh/setup.py", line 9, in <module>
        LONG_DESCRIPTION = pypandoc.convert('README.md', 'rst')
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

**Comment by arusahni** [comment]
Thanks for the report! I fixed this a while back, but didn't publish the new version. Sorry about that! I pushed a fixed version out to PyPI as v0.0.2.

Thanks for the nudge!

**Comment by rfoos** [comment]
Thanks for fixing it and getting back to me. Great package, thank you for
that too!

Rick
